-- ---------------------------------------------------------------------------
-- V11: Seed the permission matrix.
--
-- Generated by cross-joining roles x resources x operations and filtering,
-- rather than writing ~275 INSERT rows by hand -- the rule is then visible in
-- one place and cannot drift from the table it produces.
--
--   SaaSSAdmin / AppSA    every operation
--   SaaSAdmin  / AppAdmin every operation except DELETE
--   SaaSUser              VIEW and EXPORT (platform support needs to pull data)
--   AppUser               VIEW only -- deliberately no EXPORT, so a read-only
--                         parish account cannot extract a member list complete
--                         with phone numbers and addresses
--
-- SaaS and App roles share an operation set on purpose. What separates them is
-- the breadth of data they reach, which is enforced by tenant filtering, not by
-- this matrix -- exactly as section 2 of the requirements describes.
--
-- This is DATA, not structure: changing who can do what later is an INSERT or
-- DELETE here, with no migration and no redeploy.
-- ---------------------------------------------------------------------------

INSERT INTO role_permission (uuid, role_id, resource_code, operation_code, created_user)
SELECT UUID(), r.id, res.code, op.code, 'SYSTEM'
FROM role r
         CROSS JOIN (SELECT 'CHURCH' AS code
                     UNION ALL SELECT 'USER'
                     UNION ALL SELECT 'ROLE'
                     UNION ALL SELECT 'MEMBER'
                     UNION ALL SELECT 'FAMILY'
                     UNION ALL SELECT 'ANBIYAM'
                     UNION ALL SELECT 'ANBIYAM_MAPPING'
                     UNION ALL SELECT 'PAYMENT'
                     UNION ALL SELECT 'DASHBOARD'
                     UNION ALL SELECT 'REPORT'
                     UNION ALL SELECT 'AUDIT') res
         CROSS JOIN (SELECT 'ADD' AS code
                     UNION ALL SELECT 'VIEW'
                     UNION ALL SELECT 'EDIT'
                     UNION ALL SELECT 'DELETE'
                     UNION ALL SELECT 'ACTIVATE_DEACTIVATE'
                     UNION ALL SELECT 'EXPORT') op
WHERE r.deleted_flag = 0
  AND (
    -- Super admins: everything.
    (r.role_code IN ('SaaSSAdmin', 'AppSA'))
        -- Admins: everything except deletion.
        OR (r.role_code IN ('SaaSAdmin', 'AppAdmin') AND op.code <> 'DELETE')
        -- Platform support: read and extract only.
        OR (r.role_code = 'SaaSUser' AND op.code IN ('VIEW', 'EXPORT'))
        -- Ordinary parish user: read only.
        OR (r.role_code = 'AppUser' AND op.code = 'VIEW')
    );
